'use client';
import { useRef, useEffect, useState } from 'react';
import './globals.css'
import Head from 'next/head';
import Experience from '@/THREE/Expirence';
import Preloader from '@/components/Preloader';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const metadata = {
  title: 'AS',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const [loading, setLoading] = useState(true);
  const canvasRef = useRef(null);

  useEffect(() => {
    if (canvasRef.current) {
      const experience = new Experience(canvasRef.current, true);
      experience.resources.on('ready', () => {
        setLoading(false);
      });
    }
  }, []);

  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className='no-scrollbar h-screen w-full '>
        <canvas ref={canvasRef} className="webgl"></canvas>
        {
          loading ? <Preloader /> : (
            <>
              <Navbar />
              {children}
              <Footer />
            </>
          )
        }
      </body>
    </html>
  );
}
